/* Public project credentials only. Database access is restricted by Auth + RLS. */
(() => {
  'use strict';
  const URL='https://jivcksyusroudenhmjxa.supabase.co';
  const KEY='sb_publishable_Y63FLoC43cojgCTsimJQAQ_TIkLFEM8';
  const REDIRECT='https://kriskarachorov.github.io/figures-en-jeu/';
  const $=id=>document.getElementById(id);
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let client=null,user=null,stats=null,view=false,testActive=false,busy=false,authView='login',syncError='',loading=false;
  const memory=new Map();
  const key=id=>'figures-pending-v1:'+id;
  let storageWarning=false;
  function pending(id){if(memory.has(id))return memory.get(id);let rows=[];try{rows=JSON.parse(localStorage.getItem(key(id))||'[]');if(!Array.isArray(rows))rows=[]}catch{}memory.set(id,rows);return rows;}
  function savePending(id,rows){memory.set(id,rows);try{localStorage.setItem(key(id),JSON.stringify(rows))}catch{storageWarning=true;}}
  function authError(e){const c=e?.code||'',m=e?.message||'';if(c==='invalid_credentials')return 'Adresse e-mail ou mot de passe incorrect.';if(c==='email_not_confirmed')return 'Confirme ton adresse avec le lien reçu par e-mail, puis connecte-toi.';if(c==='weak_password')return 'Choisis un mot de passe plus long et plus difficile à deviner.';if(/rate|limit/i.test(c+m))return 'Trop de tentatives. Attends quelques minutes avant de réessayer.';if(/email_address_not_authorized|email.*send|smtp/i.test(c+m))return 'L’envoi des e-mails n’est pas encore disponible. Contacte Kristian pour terminer la configuration des comptes.';if(c==='user_already_exists')return 'Ce compte existe déjà. Essaie de te connecter.';if(/fetch|network/i.test(m))return 'Connexion indisponible. Vérifie Internet et réessaie.';return 'Impossible de terminer cette action. Réessaie dans un instant.';}
  function renderStrip(){const b=$('account-button');b.textContent=user?'Mon compte':'Se connecter';if(!user){$('account-strip').innerHTML='<div class="account-banner"><span>Connecte-toi pour conserver tes points et tes résultats.</span><span class="small">10 points par bonne réponse · 5 avec indice</span></div>';return;}const n=pending(user.id).length;const points=stats?Number(stats.points):null;const name=user.user_metadata?.display_name||'À toi de jouer';$('account-strip').innerHTML=`<div class="account-banner signed-in"><span><b>${escape(name)}</b></span>${testActive?'<span class="points-badge">Contrôle en cours</span>':''}</div><div class="sync-status" role="status">${testActive?'Les points du contrôle sont attribués à la fin. ':''}${syncError?escape(syncError)+' ':n?n+' réponse(s) en attente de sauvegarde. ':loading?'Actualisation…':stats?'Progression synchronisée.':'Chargement de la progression…'}${storageWarning?' Garde cet onglet ouvert jusqu’à la sauvegarde.':''}${syncError||n?'<button class="text-btn" id="sync-retry">Réessayer</button>':''}</div>`;const retry=$('sync-retry');if(retry)retry.onclick=()=>{syncError='';flush();refresh();};}
  async function refresh(){const owner=user?.id;if(!owner||!client)return;loading=true;renderStrip();try{const {data,error}=await client.rpc('get_figure_progress');if(user?.id!==owner)return;if(error)throw error;stats=data;syncError='';}catch(e){if(user?.id===owner)syncError=e.code==='PGRST202'?'La sauvegarde des résultats est en cours de configuration.':'Impossible de charger la progression. Réessaie.';}finally{if(user?.id===owner){loading=false;renderStrip();if(view)renderProgress();}}}
  async function flush(){if(busy||!client||!user)return;busy=true;const owner=user.id;try{while(user?.id===owner&&pending(owner).length){const row=pending(owner)[0];const {data:{session}}=await client.auth.getSession();if(!session||session.user.id!==owner||user?.id!==owner)break;
        // Bind this answer to its original authenticated user, even during account switches.
        const response=await fetch(URL+'/rest/v1/rpc/record_figure_answer',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({p_attempt_id:row.attemptId,p_figure_id:row.figureId,p_selected_id:row.selectedId,p_used_hint:row.hinted,p_mode:row.mode})});
        if(!response.ok){const e=await response.json().catch(()=>({}));throw e;}
        savePending(owner,pending(owner).filter(x=>x.attemptId!==row.attemptId));
      }if(user?.id===owner){syncError='';await refresh();}
    }catch(e){if(user?.id===owner){syncError=e.code==='PGRST202'?'La sauvegarde des résultats est en cours de configuration.':'Sauvegarde interrompue. Tes réponses attendent ici une nouvelle tentative.';renderStrip();}}
    finally{busy=false;if(user&&user.id!==owner)flush();}
  }
  function record(row,owner){if(!user||user.id!==owner||!client)return;const rows=pending(owner);if(!rows.some(r=>r.attemptId===row.attemptId))savePending(owner,[...rows,row]);renderStrip();flush();}
  function renderProgress(){if(!view)return;if(window.Arena){window.Arena.dashboard();return;}if(!user){$('game').innerHTML='<span class="pill">MA PROGRESSION</span><h2 style="margin-top:20px">Tes efforts, au même endroit.</h2><p>Retrouve tes points et tes résultats sur tes appareils en te connectant.</p><button class="primary" id="progress-login">Se connecter</button>';$('progress-login').onclick=()=>openAuth('login');return;}
    if(!stats){$('game').innerHTML='<span class="pill">MA PROGRESSION</span><h2 style="margin-top:20px">'+(loading?'Chargement…':'Ta progression arrive bientôt.')+'</h2><p>'+escape(syncError||'Réponds à quelques questions pour commencer.')+'</p><button class="secondary" id="progress-refresh">Actualiser</button>';$('progress-refresh').onclick=refresh;return;}
    const total=Number(stats.answered),correct=Number(stats.correct),points=Number(stats.points),level=1+Math.floor(points/100),rows=new Map((stats.figures||[]).map(f=>[f.id,f]));
    $('game').innerHTML=`<span class="pill">MA PROGRESSION</span><h2 style="margin-top:18px">Chaque réponse compte.</h2><div class="stat-grid"><div><b>${points}</b><span>points gagnés</span></div><div><b>${total?Math.round(correct/total*100)+' %':'—'}</b><span>de bonnes réponses</span></div><div><b>${total}</b><span>réponses sauvegardées</span></div></div><p><b>Niveau ${level}</b> · ${100-points%100} points jusqu’au niveau suivant</p><progress class="level-progress" value="${points%100}" max="100" aria-label="Progression dans le niveau"></progress><p class="small">10 points par bonne réponse, 5 avec indice, 0 en cas d’erreur. Les points du contrôle sont enregistrés à la fin. « À l’aise » signifie au moins 3 bonnes réponses sans indice et 80 % de réussite.</p><h3>Les 32 figures</h3><div class="figure-progress">${window.FIGURES.map(f=>{const r=rows.get(f.id),pct=r?Math.round(r.correct/r.answered*100):0,status=!r?'Pas encore vue':r.unassisted_correct>=3&&pct>=80?'À l’aise':'En cours';return `<div class="figure-stat"><div><b>${escape(f.name)}</b><span class="small">${status}</span></div><span>${r?r.correct+' / '+r.answered:'—'}</span></div>`}).join('')}</div>`;}
  function showProgress(){window.ThursdayRevision?.stop();window.Arena?.cancelWeekly();view=true;testActive=false;document.querySelectorAll('.mode').forEach(b=>{b.classList.toggle('active',b.id==='progress-mode');b.setAttribute('aria-pressed',String(b.id==='progress-mode'))});renderStrip();renderProgress();refresh();}
  function leaveProgress(){view=false;$('progress-mode').classList.remove('active');$('progress-mode').setAttribute('aria-pressed','false');}
  function showMessage(text,bad=false){const box=$('auth-message');if(box){box.textContent=text;box.className='auth-message'+(bad?' bad':'');}}
  function openAuth(v='login'){authView=v;renderAuth();if(!$('auth-dialog').open)$('auth-dialog').showModal();}
  function renderAuth(){const account=!!user&&authView!=='recovery';$('auth-title').textContent=account?'Mon compte':({login:'Content de te revoir.',signup:'Crée ton compte.',reset:'Mot de passe oublié ?',recovery:'Choisis un nouveau mot de passe.'}[authView]);
    if(account){$('auth-content').innerHTML=`<p>${escape(user.email||'Compte connecté')}</p><p class="small">Tes réponses sont privées. Ton pseudo et ton total XP sont visibles dans le classement réservé aux comptes connectés.</p><p id="auth-message" role="status"></p><button class="primary" id="logout">Se déconnecter</button>`;$('logout').onclick=async()=>{const b=$('logout');b.disabled=true;const {error}=await client.auth.signOut({scope:'local'});if(error){showMessage(authError(error),true);b.disabled=false}else $('auth-dialog').close();};return;}
    const signup=authView==='signup',reset=authView==='reset',recovery=authView==='recovery';$('auth-content').innerHTML=`<p class="small">${reset?'Reçois un lien pour changer ton mot de passe.':recovery?'Enregistre ton nouveau mot de passe pour retrouver ton compte.':'Sauvegarde ta progression. Ton pseudo et ton total XP apparaîtront dans le classement réservé aux comptes connectés.'}</p><form id="auth-form">${signup?'<label>Pseudo<input name="display_name" maxlength="30" autocomplete="nickname" required></label>':''}${!recovery?'<label>Adresse e-mail<input name="email" type="email" autocomplete="email" required></label>':''}${!reset?`<label>Mot de passe<input name="password" type="password" autocomplete="${signup||recovery?'new-password':'current-password'}" minlength="${signup||recovery?10:1}" required></label>${signup||recovery?'<p class="small">Au moins 10 caractères.</p>':''}`:''}<p id="auth-message" class="auth-message" role="status" aria-live="polite"></p><button class="primary" id="auth-submit" type="submit">${signup?'Créer mon compte':reset?'Envoyer le lien':recovery?'Enregistrer le mot de passe':'Se connecter'}</button></form>${!recovery?`<div class="auth-links"><button class="text-btn" id="auth-switch">${signup||reset?'J’ai déjà un compte':'Créer un compte'}</button>${!signup&&!reset?'<button class="text-btn" id="auth-reset">Mot de passe oublié ?</button>':''}</div>`:''}<p class="small">Les comptes et les mots de passe sont gérés par Supabase. Tu peux aussi jouer sans compte ; tes résultats ne seront alors pas sauvegardés.</p>`;
    $('auth-form').onsubmit=submitAuth;const swap=$('auth-switch');if(swap)swap.onclick=()=>{authView=signup||reset?'login':'signup';renderAuth()};const forgot=$('auth-reset');if(forgot)forgot.onclick=()=>{authView='reset';renderAuth()};}
  async function submitAuth(e){e.preventDefault();if(!client){showMessage('Connexion indisponible. Recharge la page puis réessaie.',true);return;}const v=authView,values=new FormData(e.target),email=String(values.get('email')||'').trim(),password=String(values.get('password')||''),button=$('auth-submit');button.disabled=true;showMessage('Un instant…');
    try{let result;if(v==='signup')result=await client.auth.signUp({email,password,options:{data:{display_name:String(values.get('display_name')||'').trim()},emailRedirectTo:REDIRECT}});else if(v==='reset')result=await client.auth.resetPasswordForEmail(email,{redirectTo:REDIRECT});else if(v==='recovery')result=await client.auth.updateUser({password});else result=await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;
      if(v==='reset'){showMessage('Si cette adresse peut recevoir un lien, un e-mail vient d’être envoyé. Vérifie aussi les indésirables.');}
      else if(v==='signup'&&!result.data.session){e.target.reset();showMessage('Vérifie ta boîte e-mail pour confirmer ton compte, puis connecte-toi.');}
      else{e.target.reset();if(v==='recovery')authView='login';$('auth-dialog').close();}
    }catch(err){showMessage(authError(err),true);}finally{if(button.isConnected)button.disabled=false;}}
  window.GameAccount={openAuth,api:async(name,args={},owner=user?.id)=>{const {data:{session}}=await client.auth.getSession();if(!owner||user?.id!==owner||session?.user.id!==owner)throw Error('Account changed');const r=await fetch(URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(args)});const raw=await r.text();const data=raw?JSON.parse(raw):null;if(!r.ok)throw data;if(user?.id!==owner)throw Error('Account changed');return data;},record,userId:()=>user?.id||null,showProgress,leaveProgress,isProgress:()=>view,setTestActive:v=>{testActive=v;renderStrip()}};
  $('account-button').onclick=()=>openAuth();$('auth-close').onclick=()=>$('auth-dialog').close();$('progress-mode').onclick=showProgress;
  window.addEventListener('online',()=>{flush();refresh()});
  window.addEventListener('storage',e=>{if(user&&e.key===key(user.id)){memory.delete(user.id);renderStrip();flush()}});
  renderStrip();
  try{client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    client.auth.onAuthStateChange((event,session)=>{const previous=user?.id||null;user=session?.user||null;const changed=previous!==(user?.id||null);if(changed){stats=null;syncError='';loading=false;window.dispatchEvent(new Event('account-identity-changed'));}renderStrip();if(view)renderProgress();if(event==='PASSWORD_RECOVERY')setTimeout(()=>openAuth('recovery'),0);if(user)setTimeout(()=>{flush();refresh()},0);});
  }catch{syncError='Connexion aux comptes indisponible.';}
})();
