const figures=window.FIGURES,game=document.getElementById('game');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let mode='practice',queue=[],pos=0,results=[],chosen=null,hinted=false,card=0,flipped=false,finished=false;
function start(m,ids){window.GameAccount?.leaveProgress();window.GameAccount?.setTestActive(m==='test');window.roundOwner=window.GameAccount?.userId()||null;mode=m;pos=0;results=[];chosen=null;hinted=false;finished=false;flipped=false;document.querySelectorAll('.mode').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',String(b.dataset.mode===m))});if(m==='cards'){card=0;renderCards();return}const pool=ids?figures.filter(f=>ids.includes(f.id)):figures;queue=shuffle(pool).slice(0,m==='test'?20:10).map((f,i)=>({f,attemptId:crypto.randomUUID(),kind:f.id===20?'definition':i%2===0?'example':'definition',options:shuffle([f,...shuffle(figures.filter(x=>x.id!==f.id&&!(f.id===4&&x.id===3)&&!(f.id===1&&x.id===0)&&!(f.id===24&&x.id===19))).slice(0,3)])}));render()}
function render(){const q=queue[pos];const good=results.filter(r=>r.correct&&!r.hinted).length;game.innerHTML=`<div class="question-top"><span class="pill">${mode==='test'?'CONTRÔLE BLANC':q.kind==='example'?'TROUVE LA FIGURE':'RETROUVE LE NOM'}</span><span>Question ${pos+1} / ${queue.length}</span></div><div class="progress" role="progressbar" aria-label="Questions terminées" aria-valuenow="${pos}" aria-valuemin="0" aria-valuemax="${queue.length}"><div style="width:${pos/queue.length*100}%"></div></div>${mode==='practice'?`<div class="stat-line"><span>${good} bonne${good===1?'':'s'} réponse${good===1?'':'s'} sans indice</span></div>`:''}<h2>${esc(q.kind==='example'?'« '+q.f.example+' »':q.f.definition)}</h2><p class="prompt">${q.f.id===20?'Quel nom ta fiche donne-t-elle à cette construction ?':q.kind==='example'?'Quel procédé correspond le mieux à l’effet mis en avant ?':'À quelle figure correspond cette définition ?'}</p><div class="answers">${q.options.map((f,i)=>`<button data-answer="${f.id}"><span class="key">${i+1}</span>${esc(f.name)}</button>`).join('')}</div><div id="feedback" role="status" aria-live="polite"></div><div class="actions">${mode==='practice'?'<button class="text-btn" id="hint">Besoin d’un indice ?</button>':'<span class="small">Corrections à la fin</span>'}<button id="next" class="primary hidden">${pos===queue.length-1?'Voir mon bilan':'Question suivante →'}</button></div>`;game.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));const hint=document.getElementById('hint');if(hint)hint.onclick=()=>{if(chosen!==null)return;hinted=true;document.getElementById('feedback').innerHTML=`<div class="feedback"><b>Indice</b><p>${esc(q.f.hint)}</p></div>`;hint.disabled=true;hint.textContent='Indice utilisé'};document.getElementById('next').onclick=next;}
function answer(id){if(window.GameAccount?.isProgress()||finished||mode==='cards'||chosen!==null||!queue[pos].options.some(f=>f.id===id))return false;chosen=id;const q=queue[pos],correct=id===q.f.id;results.push({q,selected:id,correct,hinted});if(mode==='practice')window.GameAccount?.record({attemptId:q.attemptId,figureId:q.f.id,selectedId:id,hinted,mode},window.roundOwner);game.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;const n=Number(b.dataset.answer);if(mode==='practice'){if(n===q.f.id)b.classList.add('right');else if(n===id)b.classList.add('wrong')}else if(n===id)b.classList.add('selected')});const fb=document.getElementById('feedback');if(mode==='practice')fb.innerHTML=`<div class="feedback ${correct?'good':'bad'}"><b>${correct?'Bien vu !':'La réponse : '+esc(q.f.name)}</b><p>${esc(q.f.explanation)}</p>${q.kind==='definition'?'<p>Exemple : « '+esc(q.f.example)+' »</p>':''}${hinted?'<p class="small">Réponse aidée : à refaire sans indice.</p>':''}</div>`;else fb.innerHTML='<div class="feedback">Réponse enregistrée.</div>';const h=document.getElementById('hint');if(h)h.classList.add('hidden');const n=document.getElementById('next');n.classList.remove('hidden');n.focus();return true;}
function next(){if(window.GameAccount?.isProgress()||chosen===null||finished)return;pos++;chosen=null;hinted=false;if(pos>=queue.length){finished=true;renderSummary()}else render();}
function renderSummary(){if(mode==='test'){for(const r of results)window.GameAccount?.record({attemptId:r.q.attemptId,figureId:r.q.f.id,selectedId:r.selected,hinted:r.hinted,mode},window.roundOwner)}window.GameAccount?.setTestActive(false);const score=results.filter(r=>r.correct).length,review=results.filter(r=>!r.correct||r.hinted);game.innerHTML=`<span class="pill">${mode==='test'?'CONTRÔLE TERMINÉ':'MANCHE TERMINÉE'}</span><h2 style="margin-top:20px">${score===queue.length?'Bien joué !':'Chaque erreur te fait avancer.'}</h2><div class="score">${score}<span> / ${queue.length}</span></div><p>${mode==='test'?'Note : '+(score/queue.length*20).toFixed(1).replace('.',',')+' / 20. ':''}${review.length?review.length+' figure(s) à revoir, y compris les réponses aidées.':'Tout est juste et sans indice. Essaie une nouvelle série.'}</p><div class="actions"><button id="again" class="primary">Nouvelle série</button>${review.length?'<button id="retry" class="secondary">Rejouer les figures à revoir</button>':''}</div><h3>Ton corrigé</h3>${results.map(r=>`<div class="review-item"><b class="${r.correct?'good':'bad'}">${r.correct?'✓':'×'} ${esc(r.q.f.name)}${r.hinted?' · avec indice':''}</b><p>${esc(r.q.kind==='example'?r.q.f.example:r.q.f.definition)}</p>${!r.correct?'<p class="bad">Ta réponse : '+esc(figures[r.selected].name)+'</p>':''}<p>${esc(r.q.f.explanation)}</p></div>`).join('')}`;document.getElementById('again').onclick=()=>start(mode);const retry=document.getElementById('retry');if(retry)retry.onclick=()=>start('practice',review.map(r=>r.q.f.id));game.scrollIntoView({behavior:'smooth',block:'start'});}
function renderCards(){const f=figures[card];game.innerHTML=`<div class="question-top"><span class="pill">FICHE MÉMO</span><span>${card+1} / ${figures.length}</span></div><select class="card-selector" aria-label="Choisir une figure">${figures.map(f=>`<option value="${f.id}" ${f.id===card?'selected':''}>${esc(f.name)}</option>`).join('')}</select><h2>${esc(f.name)}</h2>${flipped?`<p class="card-def">${esc(f.definition)}</p><div class="card-example">« ${esc(f.example)} »</div><p>${esc(f.explanation)}</p>${f.id===20?'<p class="note">Terme à confirmer avec ton professeur. Voir la précision en bas de page.</p>':''}`:'<p class="prompt">Essaie de donner la définition et un exemple, puis vérifie.</p><button class="primary" id="flip">Révéler la fiche</button>'}<div class="actions"><button class="secondary" id="prevcard">← Précédente</button><button class="secondary" id="nextcard">Suivante →</button></div>`;game.querySelector('select').onchange=e=>{card=Number(e.target.value);flipped=false;renderCards()};const flip=document.getElementById('flip');if(flip)flip.onclick=()=>{flipped=true;renderCards()};document.getElementById('prevcard').onclick=()=>{card=(card+31)%32;flipped=false;renderCards()};document.getElementById('nextcard').onclick=()=>{card=(card+1)%32;flipped=false;renderCards()};}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
document.addEventListener('keydown',e=>{if(e.repeat||document.getElementById('auth-dialog')?.open||window.GameAccount?.isProgress()||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(mode!=='cards'&&!finished&&chosen===null&&/^[1-4]$/.test(e.key)){e.preventDefault();answer(queue[pos].options[Number(e.key)-1].id)}});
start('practice');
function gameState(){if(mode==='cards')return {mode,figure:figures[card].name,revealed:flipped};if(finished)return {mode,finished:true,score:results.filter(r=>r.correct).length,total:queue.length};const q=queue[pos];return {mode,question:pos+1,total:queue.length,prompt:q.kind==='example'?q.f.example:q.f.definition,options:q.options.map(f=>({id:f.id,name:f.name})),answered:chosen!==null};}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const specs=[
{name:'read_game',description:'Read the visible question or completed score without revealing an unanswered solution.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameState()},
{name:'start_revision',description:'Start a fresh practice round, mock test or flashcard session; replaces the current round.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['practice','test','cards']}},required:['mode'],additionalProperties:false},execute:input=>{if(!input||!['practice','test','cards'].includes(input.mode))throw Error('Invalid mode');start(input.mode);return gameState()}},
{name:'submit_answer',description:'Submit one of the currently displayed answer IDs.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:0,maximum:31}},required:['id'],additionalProperties:false},execute:input=>{if(!Number.isInteger(input?.id)||!answer(input.id))throw Error('Answer unavailable or already submitted');return gameState()}},
{name:'next_question',description:'Move to the next question after answering, or show the final score.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(mode==='cards'||chosen===null||finished)throw Error('Answer the current question first');next();return gameState()}}
];for(const spec of specs){try{Promise.resolve(document.modelContext.registerTool({...spec,annotations:{readOnlyHint:false,untrustedContentHint:false,...spec.annotations}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

window.addEventListener('account-identity-changed',()=>start(mode==='cards'?'cards':'practice'));
