const figures=window.FIGURES,game=document.getElementById('game');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let mode='practice',queue=[],pos=0,results=[],chosen=null,hinted=false,card=0,flipped=false,finished=false,roundId='',reasonStage=false,nameChoice=null;
const titles={practice:'ENTRAÎNEMENT',test:'CONTRÔLE BLANC',daily:'QUÊTE DU JOUR',boss:'BOSS · FIGURES À DISTINGUER',comeback:'MES ERREURS'};
const pairs=[[2,6],[7,16],[18,19],[28,29],[23,26],[9,10]];
const alternate=[
['La vieille maison nous souriait.','La maison reçoit une expression humaine.'],
['La Liberté, une femme brisant ses chaînes, se dresse sur la place.','Une figure concrète représente l’idée abstraite de liberté.'],
['Il nous a quittés cette nuit, dit-elle en annonçant sa mort.','La formule adoucit la réalité de la mort.'],
['Elle lit un Zola.','Le nom de l’auteur désigne son œuvre.'],
['Vingt voiles quittent le port.','Les voiles, parties des bateaux, désignent les bateaux entiers.'],
['L’astre du jour apparaît.','Cette expression désigne le soleil.'],
['Ce résultat n’est pas mauvais : il est excellent !','La négation du contraire suggère un éloge plus fort.'],
['Ici je rêve. Ici je respire. Ici je reste.','Le même mot ouvre trois phrases successives.'],
['Le matin apporte la lumière ; le soir emporte la chaleur.','Les deux propositions suivent la même structure syntaxique.'],
['Une obscure clarté remplit la pièce.','Deux termes opposés sont réunis dans un même groupe.'],
['Quel génie ! dit-elle à celui qui vient de casser la porte.','Le contexte transforme le compliment en reproche ironique.'],
['Paul choisit le thé ; Léa, le café.','Le verbe « choisit » est sous-entendu dans le second segment.'],
['Il prit son manteau et la fuite.','Le verbe prendre relie un objet concret et une expression abstraite.'],
['Entre le poison et le poisson, une lettre change tout.','Les deux mots ont des sons proches et des sens différents.'],
['Je ne parlerai pas de ses retards, encore trois cette semaine.','Le locuteur évoque ce qu’il annonce vouloir taire.'],
['Ce petit Einstein résout tout.','Un nom propre devient le nom d’une personne très intelligente.'],
['Je travaille pour toi, je veille pour toi, je reste pour toi.','La même expression revient à la fin des segments.'],
['Ton palais ? Une baraque prétentieuse !','Une expression dépréciative rabaisse le bâtiment.'],
['Et la pluie, et le vent, et le froid nous attendaient.','La conjonction est répétée devant chaque élément.'],
['Le ciel se couvre, la mer se soulève, les passants rentrent.','Les propositions sont juxtaposées sans mot de liaison.'],
['Selon ta fiche : des segments de même longueur, construction et rythme.','On conserve ici le terme particulier de ta fiche : paradiastole.'],
['Les vagues, les algues, l’écume et les marées occupent son récit.','Les mots partagent un domaine de sens : la mer.'],
['Il est courageux — non, héroïque !','Le locuteur corrige et renforce sa première expression.'],
['Seul, je suis resté toute la nuit, seul.','Le même mot ouvre et ferme la phrase.'],
['Il court, saute, tombe, crie.','Les verbes courts s’accumulent et accélèrent le rythme.'],
['Tout le monde était parti. Même lui.','Un ajout prolonge une phrase qui semblait achevée.'],
['Il cherche la paix. La paix lui échappe.','La fin du premier segment devient le début du suivant.'],
['Si tu recommences, je…','La phrase s’interrompt brusquement avant son achèvement.'],
['Tout roule sous la voûte rouge.','Le son de voyelle /u/ revient dans tout, roule, sous, voûte et rouge.'],
['Six serpents sifflent sur le sable.','La consonne /s/ est répétée.'],
['La porte claque. Une tasse se brise, le café coule sur le carrelage ; une main tremblante ramasse les éclats.','Des détails concrets et des actions au présent rendent la scène visible.'],
['Ô nuit, protège nos secrets !','Le locuteur s’adresse directement à la nuit.']];
function start(m,ids){window.ThursdayRevision?.stop();Arena.cancelWeekly();GameAccount.leaveProgress();GameAccount.setTestActive(m==='test');window.roundOwner=GameAccount.userId();mode=m;pos=0;results=[];chosen=null;hinted=false;finished=false;flipped=false;reasonStage=false;roundId=crypto.randomUUID();document.querySelectorAll('.mode').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',String(b.dataset.mode===m))});if(!GameAccount.requireLogin()){finished=true;queue=[];return}if(m==='thursday'){finished=true;ThursdayRevision.start();return}if(m==='weekly'||m==='leaderboard'){finished=true;Arena[m==='weekly'?'weekly':'leaderboard']();return}if(m==='cards'){card=0;renderCards();return}if(m==='comeback'&&!ids)ids=Arena.missed();if(ids&&!ids.length){finished=true;game.innerHTML='<span class="pill">MES ERREURS</span><h2>Aucune erreur à revoir.</h2><p>Les figures à revoir apparaîtront ici après une manche.</p><button class="primary" id="empty-play">Jouer une manche</button>';document.getElementById('empty-play').onclick=()=>start('practice');return}let pool=ids?figures.filter(f=>ids.includes(f.id)):shuffle(figures);if(m==='daily'){const offset=Math.floor(Date.now()/86400000)%32;pool=Array.from({length:5},(_,i)=>figures[(offset+i*7)%32])}if(m==='boss')pool=shuffle(pairs).slice(0,3).flatMap(p=>p.map(id=>figures[id]));queue=pool.slice(0,m==='test'?20:m==='daily'?5:10).map((base,i)=>{const f=m==='comeback'||m==='boss'?{...base,example:alternate[base.id][0],explanation:alternate[base.id][1]}:base;const pair=pairs.find(p=>p.includes(f.id));return {f,attemptId:crypto.randomUUID(),kind:f.id===20?'definition':m==='boss'||m==='comeback'?'example':i%2?'definition':'example',options:shuffle(m==='boss'?pair.map(id=>figures[id]):[f,...shuffle(figures.filter(x=>x.id!==f.id&&!(f.id===4&&x.id===3)&&!(f.id===1&&x.id===0)&&!(f.id===24&&x.id===19))).slice(0,3)])}});render()}
function combo(){let n=0;for(let i=results.length-1;i>=0&&results[i].correct&&!results[i].hinted;i--)n++;return n}
function render(){const q=queue[pos];reasonStage=false;nameChoice=null;game.innerHTML=`<div class="question-top"><span class="pill">${titles[mode]}</span><span>${pos+1} / ${queue.length}</span></div><progress value="${pos}" max="${queue.length}" aria-label="Questions terminées"></progress>${mode!=='test'?`<p class="combo ${combo()>=3?'hot':''}">${combo()>=3?'✦ Combo '+combo():'Sans chronomètre'}</p>`:''}<h2>${esc(q.kind==='example'?'« '+q.f.example+' »':q.f.definition)}</h2><p class="prompt">${mode==='boss'?'Étape 1 sur 2 · Choisis la figure, puis explique le mécanisme.':q.f.id===20?'Quel nom ta fiche donne-t-elle à cette construction ?':'Quel procédé correspond le mieux à cet effet ?'}</p><div class="answers">${q.options.map((f,i)=>`<button data-answer="${f.id}"><span class="key">${i+1}</span>${esc(f.name)}</button>`).join('')}</div><div id="feedback" role="status" aria-live="polite"></div><div class="actions">${!['test','boss'].includes(mode)?'<button class="text-btn" id="hint">Besoin d’un indice ?</button>':'<span class="small">Correction après '+(mode==='boss'?'les deux étapes':'le contrôle')+'</span>'}<button id="next" class="primary hidden">${pos===queue.length-1?'Voir mon bilan':'Continuer →'}</button></div>`;bindAnswers();const hint=document.getElementById('hint');if(hint)hint.onclick=()=>{if(chosen!==null)return;hinted=true;document.getElementById('feedback').innerHTML='<div class="feedback"><b>Indice</b><p>'+esc(q.f.hint)+'</p></div>';hint.disabled=true};document.getElementById('next').onclick=next}
function bindAnswers(){game.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)))}
function answer(id){if(!GameAccount.userId()||GameAccount.userId()!==window.roundOwner||GameAccount.isProgress()||finished||mode==='cards'||chosen!==null||!queue[pos]?.options.some(f=>f.id===id))return false;const q=queue[pos];if(mode==='boss'&&!reasonStage){Arena.celebrate('tap');nameChoice=id;reasonStage=true;game.querySelector('.prompt').textContent='Étape 2 sur 2 · Quel mécanisme explique la phrase ?';game.querySelector('.answers').innerHTML=q.options.map((f,i)=>`<button data-answer="${f.id}"><span class="key">${i+1}</span>${esc(f.definition)}</button>`).join('');bindAnswers();return true}chosen=id;const selected=mode==='boss'?nameChoice:id,correct=selected===q.f.id&&(mode!=='boss'||id===q.f.id);results.push({q,selected,reasonId:mode==='boss'?id:null,correct,hinted});game.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;const n=Number(b.dataset.answer);if(mode!=='test'){if(n===q.f.id)b.classList.add('right');else if(n===id)b.classList.add('wrong')}else if(n===id)b.classList.add('selected')});document.getElementById('feedback').innerHTML=mode==='test'?'<div class="feedback">Réponse enregistrée.</div>':`<div class="feedback ${correct?'good':'bad'}"><b>${correct?(combo()>=3?'✦ Combo '+combo()+'':'Correct'):'À retenir : '+esc(q.f.name)}</b><p>${esc(q.f.explanation)}</p>${mode==='boss'&&!correct?'<p>Il faut identifier la figure et son mécanisme pour réussir le duel.</p>':''}${hinted?'<p class="small">À refaire sans indice pour remplir ton anneau.</p>':''}</div>`;Arena.celebrate(mode==='test'?'tap':correct?combo():'wrong');const fx=document.getElementById('feedback');if(mode!=='test')fx.insertAdjacentHTML('afterbegin',`<div class="answer-signal ${correct?'success':'retry'}" aria-hidden="true">${correct?'✓ '+(combo()>=3?'Combo '+combo():'Correct'):'↗ À revoir'}</div>`);const h=document.getElementById('hint');if(h)h.hidden=true;const n=document.getElementById('next');n.classList.remove('hidden');n.focus();return true}
function next(){if(!GameAccount.userId()||GameAccount.userId()!==window.roundOwner||GameAccount.isProgress()||chosen===null||finished)return;pos++;chosen=null;hinted=false;if(pos>=queue.length){finished=true;renderSummary()}else render()}
function renderSummary(){Arena.celebrate('finish');GameAccount.setTestActive(false);const score=results.filter(r=>r.correct).length,review=results.filter(r=>!r.correct||r.hinted),savedId=roundId,oldBadges=Arena.earnedBadges();game.innerHTML=`<span class="pill">MANCHE TERMINÉE</span><h2>${score===queue.length?'Série terminée !':'Tes résultats'}</h2><div class="score">${score}<span> / ${queue.length}</span></div><p id="round-reward" role="status">Calcul des récompenses…</p><p>${mode==='test'?'Note : '+(score/queue.length*20).toFixed(1)+' / 20. ':''}${review.length?review.length+' figure(s) à consolider.':'Toutes les réponses sont correctes.'}</p><div class="actions"><button id="again" class="primary">Nouvelle manche</button>${review.length?'<button id="retry" class="secondary">Revoir mes erreurs</button>':''}<button id="see-path" class="secondary">Statistiques</button></div><h3>Corrigé</h3>${results.map(r=>`<div class="review-item"><b class="${r.correct?'good':'bad'}">${r.correct?'✓':'↗'} ${esc(r.q.f.name)}${r.hinted?' · avec indice':''}</b><p>${esc(r.q.kind==='example'?r.q.f.example:r.q.f.definition)}</p>${!r.correct?'<p>Ton choix : '+esc(figures[r.selected].name)+'</p>':''}<p>${esc(r.q.f.explanation)}</p></div>`).join('')}`;document.getElementById('again').onclick=()=>start(mode);document.getElementById('see-path').onclick=()=>GameAccount.showProgress();const retry=document.getElementById('retry');if(retry)retry.onclick=()=>start('comeback',review.map(r=>r.q.f.id));Arena.complete({id:savedId,mode,answers:results.map(r=>({attemptId:r.q.attemptId,figureId:r.q.f.id,selectedId:r.selected,hinted:r.hinted,reasonId:r.reasonId}))},window.roundOwner).then(x=>{if(roundId===savedId&&document.getElementById('round-reward'))document.getElementById('round-reward').textContent=x===null?'Récompenses en attente de synchronisation.':'✦ +'+x+' XP'+(GameAccount.userId()?' sauvegardés':' pour cet essai')+(Arena.earnedBadges().filter(b=>!oldBadges.includes(b)).length?' · Badge débloqué : '+Arena.earnedBadges().filter(b=>!oldBadges.includes(b)).join(', '):'')});game.scrollIntoView({block:'start'})}
function renderCards(){const f=figures[card];game.innerHTML=`<div class="question-top"><span class="pill">FICHE MÉMO</span><span>${card+1} / ${figures.length}</span></div><select class="card-selector" aria-label="Choisir une figure">${figures.map(f=>`<option value="${f.id}" ${f.id===card?'selected':''}>${esc(f.name)}</option>`).join('')}</select><h2>${esc(f.name)}</h2>${flipped?`<p class="card-def">${esc(f.definition)}</p><div class="card-example">« ${esc(f.example)} »</div><p>${esc(f.explanation)}</p>`:'<p class="prompt">Essaie de donner la définition et un exemple, puis vérifie.</p><button class="primary" id="flip">Révéler la fiche</button>'}<div class="actions"><button class="secondary" id="prevcard">← Précédente</button><button class="secondary" id="nextcard">Suivante →</button></div>`;game.querySelector('select').onchange=e=>{card=Number(e.target.value);flipped=false;renderCards()};const flip=document.getElementById('flip');if(flip)flip.onclick=()=>{flipped=true;renderCards()};document.getElementById('prevcard').onclick=()=>{card=(card+31)%32;flipped=false;renderCards()};document.getElementById('nextcard').onclick=()=>{card=(card+1)%32;flipped=false;renderCards()};}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
document.addEventListener('keydown',e=>{if(e.repeat||document.getElementById('auth-dialog')?.open||GameAccount.isProgress()||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(mode!=='cards'&&!finished&&chosen===null&&/^[1-4]$/.test(e.key)){const option=queue[pos]?.options[Number(e.key)-1];if(option){e.preventDefault();answer(option.id)}}});
start('practice');
window.addEventListener('account-identity-changed',()=>start(mode));
window.addEventListener('account-session-ready',()=>start(mode));
function gameState(){if(!GameAccount.userId())return {loginRequired:true};if(mode==='thursday')return ThursdayRevision.state();if(mode==='weekly'||mode==='leaderboard')return {mode,view:game.textContent};if(mode==='cards')return {mode,figure:figures[card].name,revealed:flipped};if(finished)return {mode,finished:true,score:results.filter(r=>r.correct).length,total:queue.length};const q=queue[pos];return {mode,question:pos+1,total:queue.length,prompt:q.kind==='example'?q.f.example:q.f.definition,options:q.options.map(f=>({id:f.id,name:f.name})),answered:chosen!==null};}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const specs=[
{name:'read_game',description:'Read the visible question or completed score without revealing an unanswered solution.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameState()},
{name:'start_revision',description:'Start a fresh practice round, Thursday revision quiz or flashcard session; replaces the current round.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['practice','thursday','cards']}},required:['mode'],additionalProperties:false},execute:input=>{if(!input||!['practice','thursday','cards'].includes(input.mode))throw Error('Invalid mode');start(input.mode);return gameState()}},
{name:'submit_answer',description:'Submit one of the currently displayed answer IDs.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:0,maximum:31}},required:['id'],additionalProperties:false},execute:input=>{if(!Number.isInteger(input?.id)||!(mode==='thursday'?ThursdayRevision.answer(input.id):answer(input.id)))throw Error('Answer unavailable or already submitted');return gameState()}},
{name:'next_question',description:'Move to the next question after answering, or show the final score.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(mode==='thursday'){if(!ThursdayRevision.next())throw Error('Answer the current question first');return gameState()}if(mode==='cards'||chosen===null||finished)throw Error('Answer the current question first');next();return gameState()}}
];for(const spec of specs){try{Promise.resolve(document.modelContext.registerTool({...spec,annotations:{readOnlyHint:false,untrustedContentHint:false,...spec.annotations}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
