/* Rewards require an authenticated account and are saved with idempotent round IDs. */
(() => {
const $=id=>document.getElementById(id), safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=()=>({legacy_points:0,weekly_xp:0,rounds:[],attempts:[],quests:[]});let state=empty(),owner=null,busy=false,error='',sound=false,motion=true;
try{sound=localStorage.getItem('figures-sound')==='true';motion=localStorage.getItem('figures-motion')!=='false'}catch{}
const day=()=>new Date().toISOString().slice(0,10), key=u=>'figures-rounds-v2:'+u;const memory=new Map();
function pending(u){if(!memory.has(u)){try{const rows=JSON.parse(localStorage.getItem(key(u))||'[]');memory.set(u,Array.isArray(rows)?rows:[])}catch{memory.set(u,[])}}return memory.get(u)}
function save(u,rows){memory.set(u,rows);try{localStorage.setItem(key(u),JSON.stringify(rows))}catch{error='Garde cet onglet ouvert jusqu’à la sauvegarde.'}}
function xp(){return Number(state.legacy_points)+Number(state.weekly_xp)+state.rounds.reduce((s,r)=>s+r.earned,0)}
function mastery(id){const a=state.attempts.filter(a=>a.figureId===id);const days=new Set(a.filter(a=>a.correct&&!a.hinted).map(a=>a.date.slice(0,10)));return Math.min(3,days.size)}
function missed(){const latest=new Map();state.attempts.forEach(a=>latest.set(a.figureId,a));return [...latest.values()].filter(a=>!a.correct||a.hinted).map(a=>a.figureId)}
function badges(){return [['★','Premier pas','Terminer une manche',state.rounds.length>0],['◆','Sans faute','Une manche parfaite sans indice',state.rounds.some(r=>r.answers.every(a=>a.figureId===a.selectedId&&!a.hinted&&(r.mode!=='boss'||a.reasonId===a.figureId)))],['♫','Oreille fine','Maîtriser assonance et allitération',mastery(28)===3&&mastery(29)===3],['↗','Rebond','Corriger 5 erreurs',state.rounds.reduce((s,r)=>s+r.comeback,0)>=5],['♜','Boss vaincu','Réussir un boss sans erreur',state.rounds.some(r=>r.mode==='boss'&&r.best_combo===r.answers.length)],['✦','Collection complète','Maîtriser les 32 figures',window.FIGURES.every(f=>mastery(f.id)===3)]]}
function chrome(){const n=xp(),level=1+Math.floor(n/200);$('journey').innerHTML=`<div><span class="eyebrow">XP</span><h3>Niveau ${level} · ${n} XP</h3><progress value="${n%200}" max="200" aria-label="Expérience du niveau"></progress><span class="small">${n} XP · ${200-n%200} avant le prochain niveau</span></div><div class="quest-mini"><b>✦ Quête du jour</b><p>${state.quests.includes(day())?'Terminée ! +25 XP':'5 figures différentes sans indice'}</p><span class="small">Renouvelée à minuit UTC · aucune pénalité</span></div>`;const status=$('arena-status');status.textContent=error||(owner&&pending(owner).length?'Manche en attente de sauvegarde.':owner?'Récompenses synchronisées.':'Connecte-toi pour jouer.');$('sync-game').hidden=!(owner&&(error||pending(owner).length));document.body.classList.toggle('no-motion',!motion);$('sound-toggle').textContent=sound?'Son : oui':'Son : non';$('motion-toggle').textContent=!motion?'Animations : non':window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'Animations : réduites (système)':'Animations : oui';}
async function refresh(){const u=window.GameAccount.userId();if(!u){owner=null;chrome();return}owner=u;try{const data=await window.GameAccount.api('get_game_state',{},u);if(owner!==u)return;state=data;error='';chrome()}catch(e){if(owner===u){error=e.code==='PGRST202'?'La mise à jour des récompenses attend le script Supabase.':'Progression indisponible. Réessaie.';chrome()}}}
async function flush(){if(busy||!owner)return;busy=true;const u=owner;try{while(owner===u&&pending(u).length){const r=pending(u)[0];await window.GameAccount.api('submit_game_round',{p_id:r.id,p_mode:r.mode,p_answers:r.answers},u);save(u,pending(u).filter(x=>x.id!==r.id));window.RankNotice?.check({round:r.id},u)}if(owner===u)await refresh()}catch{if(owner===u){error='Sauvegarde en attente. Tes manches restent sur cet appareil.';chrome()}}finally{busy=false;if(owner&&owner!==u)flush()}}
async function complete(r,u){if(!u||u!==window.GameAccount.userId())return null;owner=u;save(u,[...pending(u).filter(x=>x.id!==r.id),r]);await flush();return state.rounds.find(x=>x.id===r.id)?.earned??null}
let audioContext=null,master=null;
async function celebrate(value=0){
 if(!sound)return;
 try{
  const Audio=window.AudioContext||window.webkitAudioContext;
  if(!Audio)throw Error('Audio unavailable');
  if(!audioContext||audioContext.state==='closed'){audioContext=new Audio();master=audioContext.createGain();master.connect(audioContext.destination)}
  if(audioContext.state==='suspended')await audioContext.resume();
  if(!sound)return;
  master.gain.setValueAtTime(.14,audioContext.currentTime);
  const notes=value==='wrong'?[220,174]:value==='tap'?[390]:value==='finish'?[523,659,784]:value>=3?[523,659,880]:[523,659];
  notes.forEach((frequency,i)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),at=audioContext.currentTime+i*.085;oscillator.type='sine';oscillator.frequency.value=frequency;oscillator.connect(gain);gain.connect(master);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(.7,at+.012);gain.gain.exponentialRampToValueAtTime(.001,at+.19);oscillator.start(at);oscillator.stop(at+.20);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()}});
 }catch{if($('arena-status'))$('arena-status').textContent='Son indisponible dans ce navigateur.'}
}
function dashboard(){if(!GameAccount.requireLogin())return;const rounds=state.rounds,total=state.attempts.length,correct=state.attempts.filter(a=>a.correct).length;const tests=rounds.filter(r=>r.mode==='test').map(r=>r.answers.filter(a=>a.figureId===a.selectedId).length/r.answers.length*20);$('game').innerHTML=`<span class="pill">STATISTIQUES</span><h2>Ta progression</h2><div class="stat-grid"><div><b>${total?Math.round(correct/total*100):0}%</b><span>réussite globale</span></div><div><b>${Math.max(0,...rounds.map(r=>r.best_combo))}</b><span>meilleur combo</span></div><div><b>${tests.length?Math.max(...tests).toFixed(1)+'/20':'—'}</b><span>meilleur contrôle</span></div></div><h3>Badges</h3><div class="badges">${badges().map(([icon,name,desc,yes])=>`<div class="badge ${yes?'unlocked':''}"><b>${icon}</b><strong>${name}</strong><span>${desc}</span><small>${yes?'Débloqué':'À découvrir'}</small></div>`).join('')}</div><h3>Maîtrise des 32 figures</h3><p class="small">Un anneau par jour de réussite sans indice. Trois jours différents pour maîtriser une figure. Clique pour la réviser.</p><div class="mastery">${window.FIGURES.map(f=>`<button data-study="${f.id}"><span class="ring" style="--fill:${mastery(f.id)/3*100}%">${mastery(f.id)===3?'✓':mastery(f.id)+'/3'}</span>${safe(f.name)}</button>`).join('')}</div><p class="small">10 XP par bonne réponse, 5 avec indice, jusqu’à deux réponses récompensées par figure et par jour UTC. Combo de 5 : +5 XP ; boss parfait : +10 ; erreur corrigée en revanche : +5. Les récompenses sont attribuées à la fin de la manche. </p>`;$('game').querySelectorAll('[data-study]').forEach(b=>b.onclick=()=>window.start('practice',[Number(b.dataset.study)]))}
let weeklyTicket=0;
async function leaderboard(){
 const ticket=++weeklyTicket,u=window.GameAccount.userId();
 if(!u){$('game').innerHTML='<span class="pill">CLASSEMENT XP</span><h2>Compare tes XP</h2><p>Connecte-toi pour voir le classement des comptes.</p><button class="primary" id="ranking-login">Se connecter</button>';$('ranking-login').onclick=()=>GameAccount.openAuth();return}
 $('game').innerHTML='<h2>Classement XP</h2><p role="status">Chargement…</p>';
 try{const data=await GameAccount.api('get_xp_leaderboard',{},u);if(ticket!==weeklyTicket||u!==GameAccount.userId())return;
 const row=r=>`<tr class="${r.me?'my-rank':''}"><td>#${r.rank}</td><th scope="row">${safe(r.nickname)}${r.me?' <span class="pill">Toi</span>':''}</th><td><b>${Number(r.xp).toLocaleString('fr-FR')} XP</b></td></tr>`;
 $('game').innerHTML=`<span class="pill">CLASSEMENT XP</span><h2>Le classement</h2><p>Total des XP enregistrés · visible uniquement aux comptes connectés.</p>${data.me?`<div class="my-position">Ta place : <b>#${data.me.rank}</b> · ${Number(data.me.xp).toLocaleString('fr-FR')} XP</div>`:''}<table class="ranking"><thead><tr><th>Rang</th><th>Joueur</th><th>XP</th></tr></thead><tbody>${data.players.map(row).join('')}</tbody></table><p class="small">100 premiers joueurs. Même total, même rang. Ton pseudo est celui choisi à l’inscription. Les réponses et les e-mails restent privés.</p><button class="secondary" id="ranking-refresh">Actualiser</button>`;$('ranking-refresh').onclick=leaderboard;
 }catch{if(ticket!==weeklyTicket)return;$('game').innerHTML='<h2>Classement indisponible</h2><p>Réessaie après avoir vérifié la connexion et installé la mise à jour Supabase.</p><button class="secondary" id="ranking-refresh">Réessayer</button>';$('ranking-refresh').onclick=leaderboard}
}
async function weekly(){const ticket=++weeklyTicket,u=window.GameAccount.userId();window.GameAccount.leaveProgress();window.GameAccount.setTestActive(false);if(!u){$('game').innerHTML='<h2>Défi entre amis</h2><p>Les mêmes 10 questions pour tout le monde. Une note par compte chaque semaine, sans chronomètre.</p><button class="primary" id="weekly-login">Se connecter</button>';$('weekly-login').onclick=()=>window.GameAccount.openAuth();return} $('game').innerHTML='<h2>Chargement du défi…</h2>';try{const pack=await window.GameAccount.api('start_weekly',{},u);if(ticket!==weeklyTicket||u!==window.GameAccount.userId())return;if(pack.submitted){await board(pack,u,ticket);return}let i=0,answers=[];const draw=()=>{const q=pack.questions[i];$('game').innerHTML=`<span class="pill">DÉFI DE LA SEMAINE · ${i+1}/10</span><p class="small">Une note par compte · classement facultatif · corrections à la fin</p><h2>${safe(q.prompt)}</h2><div class="answers">${q.options.map(o=>`<button data-weekly="${o.id}">${safe(o.name)}</button>`).join('')}</div>`;$('game').querySelectorAll('[data-weekly]').forEach(b=>b.onclick=()=>{celebrate('tap');answers.push({id:q.id,selectedId:Number(b.dataset.weekly)});if(++i<10)draw();else finish()})};const finish=()=>{$('game').innerHTML='<h2>Prêt à valider ?</h2><p>Ton score sera enregistré une seule fois cette semaine. Tu pourras choisir ensuite de le partager.</p><button class="primary" id="weekly-send">Valider mes 10 réponses</button><p id="weekly-error" role="status"></p>';$('weekly-send').onclick=async()=>{$('weekly-send').disabled=true;try{const result=await window.GameAccount.api('submit_weekly',{p_week:pack.week,p_answers:answers,p_public:false,p_nickname:'Joueur'},u);if(ticket!==weeklyTicket)return;celebrate('finish');await refresh();await board({...pack,submitted:true,score:result.score,justSubmitted:!result.replayed},u,ticket)}catch{$('weekly-error').textContent='Envoi impossible. Réessaie ; ta note ne sera pas doublée.';$('weekly-send').disabled=false}}};draw()}catch{if(ticket===weeklyTicket)$('game').innerHTML='<h2>Défi indisponible pour le moment</h2><p>Vérifie la connexion ou réessaie après la mise à jour Supabase.</p>'}}
async function board(pack,u,ticket){const rows=await window.GameAccount.api('weekly_leaderboard',{},u);if(ticket!==weeklyTicket||u!==window.GameAccount.userId())return;$('game').innerHTML=`<span class="pill">DÉFI VALIDÉ · SEMAINE DU ${safe(pack.week)}</span><h2>${pack.score} / 10</h2><div id="rank-notice" class="rank-notice" data-result="week:${safe(pack.week)}" role="status" aria-live="polite" hidden></div><p>+${pack.score*10} XP · Prochain défi lundi à 00:00 UTC.</p><label>Pseudo public <input id="weekly-name" maxlength="30" placeholder="Ton pseudo"></label><label><input type="checkbox" id="weekly-public" ${pack.public_score?'checked':''}> Afficher mon pseudo et mon score dans le classement</label><button class="secondary" id="weekly-share">Enregistrer mon choix</button><p id="share-status" role="status"></p><h3>Entre amis</h3><p class="small">Classé par bonnes réponses. Les ex æquo partagent leur rang.</p>${rows.length?rows.map(r=>`<div class="figure-stat"><b>#${r.rank} ${safe(r.nickname)}</b><span>${r.score}/10</span></div>`).join(''):'<p>Aucun score partagé pour le moment.</p>'}<details><summary>Revoir les réponses</summary>${pack.questions.map(q=>`<p><b>${safe(window.FIGURES[q.id].name)}</b> — ${safe(q.prompt)}</p>`).join('')}</details>`;if(pack.justSubmitted)window.RankNotice?.check({week:pack.week},u);$('weekly-share').onclick=async()=>{const visible=$('weekly-public').checked,name=$('weekly-name').value.trim();if(visible&&!name){$('share-status').textContent='Choisis un pseudo pour partager ton score.';return}$('weekly-share').disabled=true;try{await window.GameAccount.api('set_weekly_visibility',{p_public:visible,p_nickname:name},u);await board({...pack,public_score:visible},u,ticket)}catch{$('share-status').textContent='Impossible d’enregistrer. Réessaie.';$('weekly-share').disabled=false}}}
window.Arena={earnedBadges:()=>badges().filter(b=>b[3]).map(b=>b[1]),complete,dashboard,missed,celebrate,weekly,leaderboard,cancelWeekly:()=>weeklyTicket++,refresh};
$('sound-toggle').onclick=()=>{sound=!sound;if(!sound&&master)master.gain.setValueAtTime(0,audioContext.currentTime);try{localStorage.setItem('figures-sound',sound)}catch{}chrome();celebrate(3)};$('motion-toggle').onclick=()=>{motion=!motion;try{localStorage.setItem('figures-motion',motion)}catch{}chrome();if(motion){$('journey').classList.remove('motion-preview');void $('journey').offsetWidth;$('journey').classList.add('motion-preview')}};$('sync-game').onclick=()=>{refresh().then(flush)};
window.addEventListener('account-identity-changed',()=>{weeklyTicket++;owner=window.GameAccount.userId();state=empty();error='';chrome();refresh().then(flush)});window.addEventListener('online',()=>refresh().then(flush));chrome();if(window.GameAccount.userId())refresh().then(flush);
})();
