(() => {
 'use strict';
 const bank=window.THURSDAY_FIGURES,$=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=items=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
 let active=false,queue=[],index=0,answers=[],selected=null,hinted=false,finished=false,owner=null,history,storageOK=true;
 const storageKey=()=> 'figures-thursday-2026-09-24:'+owner;
 function load(){try{const data=JSON.parse(localStorage.getItem(storageKey())||'null');return data&&Array.isArray(data.mistakes)&&Number.isFinite(data.rounds)?data:{rounds:0,best:null,mistakes:[]}}catch{return {rounds:0,best:null,mistakes:[]}}}
 function save(){try{localStorage.setItem(storageKey(),JSON.stringify(history))}catch{storageOK=false}}
 function controls(){return `<div class="revision-toolbar"><span class="pill">CONTRÔLE · JEUDI 24 SEPTEMBRE</span><div class="revision-actions"><button class="secondary" id="revision-all">Quiz · 24 figures</button><button class="secondary" id="revision-mistakes" ${history.mistakes.length?'':'disabled'}>Mes erreurs${history.mistakes.length?' · '+history.mistakes.length:''}</button><button class="secondary" id="revision-cards">Fiches · 24 figures</button></div></div>`}
 function bindControls(){ $('revision-all').onclick=()=>begin();$('revision-mistakes').onclick=()=>begin(history.mistakes);$('revision-cards').onclick=cards }
 function begin(ids){if(!GameAccount.requireLogin()){active=false;return}active=true;finished=false;owner=GameAccount.userId();history=load();answers=[];index=0;selected=null;hinted=false;
  const pool=ids?bank.filter(f=>ids.includes(f.id)):bank;
  queue=shuffle(pool).map((f,i)=>{const kind=(i+history.rounds)%3===0||f.name==='Tmésis'?'definition':'example';const example=f.examples[(i+history.rounds)%f.examples.length];const excluded=kind==='example'?({'Homéotéleute':['Paronomase'],'Paronomase':['Homéotéleute'],'Adynaton':['Hyperbole'],'Hyperbole':['Adynaton'],'Zeugma':['Syllepse'],'Syllepse':['Zeugma']}[f.name]||[]):[];return {f,kind,example,options:shuffle([f,...shuffle(bank.filter(x=>x.id!==f.id&&!excluded.includes(x.name))).slice(0,3)])}});
  render();
 }
 function render(){const q=queue[index];$('game').innerHTML=controls()+`<div class="question-top"><span>${q.kind==='definition'?'Définition':'Exemple'}</span><span>Question ${index+1} / ${queue.length}</span></div><progress value="${index}" max="${queue.length}" aria-label="Questions terminées"></progress><h2>${escape(q.kind==='definition'?q.f.definition:'« '+q.example[0]+' »')}</h2><p class="prompt">Quelle figure de style correspond ${q.kind==='definition'?'à cette définition':'au procédé utilisé'} ?</p><div class="answers">${q.options.map((f,i)=>`<button data-revision-answer="${f.id}"><span class="key">${i+1}</span>${escape(f.name)}</button>`).join('')}</div><div id="revision-feedback" aria-live="polite" role="status"></div><div class="actions"><button class="text-btn" id="revision-hint">Indice</button><button class="primary hidden" id="revision-next">${index+1===queue.length?'Voir les résultats':'Continuer →'}</button></div><p class="small revision-note">Uniquement les 24 figures des deux feuilles. Score de révision sur cet appareil, séparé des XP.</p>`;
  bindControls();document.querySelectorAll('[data-revision-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.revisionAnswer)));$('revision-next').onclick=next;$('revision-hint').onclick=()=>{hinted=true;$('revision-hint').disabled=true;$('revision-feedback').innerHTML='<div class="feedback">'+escape(q.f.hint)+'</div>'};
 }
 function answer(id){if(!GameAccount.userId()||GameAccount.userId()!==owner||!active||finished||selected!==null||!queue[index]?.options.some(f=>f.id===id))return false;selected=id;const q=queue[index],correct=id===q.f.id;answers.push({q,selected:id,correct,hinted});
  document.querySelectorAll('[data-revision-answer]').forEach(b=>{b.disabled=true;const n=Number(b.dataset.revisionAnswer);if(n===q.f.id)b.classList.add('right');else if(n===id)b.classList.add('wrong')});
  $('revision-feedback').innerHTML=`<div class="answer-signal ${correct?'success':'retry'}">${correct?'✓ Correct':'↗ '+escape(q.f.name)}</div><div class="feedback ${correct?'good':'bad'}"><p>${escape(q.kind==='definition'?q.f.definition:q.example[1])}</p>${q.kind==='definition'?'<p>Exemple : « '+escape(q.example[0])+' »</p><p>'+escape(q.example[1])+'</p>':''}</div>`;
  $('revision-hint').hidden=true;$('revision-next').classList.remove('hidden');$('revision-next').focus();Arena.celebrate(correct?1:'wrong');return true;
 }
 function next(){if(!GameAccount.userId()||GameAccount.userId()!==owner||!active||selected===null||finished)return false;index++;selected=null;hinted=false;if(index===queue.length)summary();else render();return true}
 function summary(){finished=true;const correct=answers.filter(a=>a.correct).length,unaided=answers.filter(a=>a.correct&&!a.hinted).length;const misses=new Set(history.mistakes);answers.forEach(a=>{if(!a.correct||a.hinted)misses.add(a.q.f.id);else misses.delete(a.q.f.id)});history.mistakes=[...misses];history.rounds++;if(queue.length===24)history.best=Math.max(history.best||0,correct);if(GameAccount.userId()===owner)save();
  $('game').innerHTML=controls()+`<h2>Résultats</h2><div class="score">${correct}<span> / ${queue.length}</span></div><p>${unaided} réponse(s) correcte(s) sans indice.${queue.length===24?' Note indicative : '+(correct/24*20).toFixed(1).replace('.',',')+' / 20.':''}</p><p class="small">${storageOK?'Meilleur quiz complet : '+(history.best===null?'—':history.best+' / 24')+' · Résultats enregistrés sur cet appareil.':'Stockage indisponible : ces résultats resteront uniquement pendant cette session.'}</p><h3>Corrigé</h3>${answers.map(a=>`<div class="review-item"><b class="${a.correct?'good':'bad'}">${a.correct?'✓':'×'} ${escape(a.q.f.name)}${a.hinted?' · avec indice':''}</b><p>${escape(a.q.kind==='definition'?a.q.f.definition:a.q.example[0])}</p>${!a.correct?'<p>Ton choix : '+escape(bank[a.selected].name)+'</p>':''}<p>${escape(a.q.example[1])}</p></div>`).join('')}`;bindControls();Arena.celebrate('finish');$('game').scrollIntoView({block:'start'});
 }
 function cards(){if(!GameAccount.requireLogin())return;finished=true;$('game').innerHTML=controls()+'<h2>Les 24 figures du contrôle</h2><div class="revision-cards">'+bank.map(f=>`<details><summary>${escape(f.name)}</summary><p>${escape(f.definition)}</p>${f.examples.map(([text,explanation])=>`<blockquote>${escape(text)}</blockquote><p class="small">${escape(explanation)}</p>`).join('')}</details>`).join('')+'</div>';bindControls()}
 document.addEventListener('keydown',e=>{if(!active||finished||selected!==null||e.repeat||$('auth-dialog')?.open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const n=Number(e.key);if(n>=1&&n<=4&&Number.isInteger(n)){e.preventDefault();answer(queue[index].options[n-1].id)}});
 window.ThursdayRevision={start:begin,stop:()=>{active=false},answer,next,state:()=>({mode:'thursday',finished,question:index+1,total:queue.length,answered:selected!==null,prompt:queue[index]?(queue[index].kind==='definition'?queue[index].f.definition:queue[index].example[0]):null,options:queue[index]?.options.map(f=>({id:f.id,name:f.name}))||[]})};
})();
