(() => {
 'use strict';
 const bank=window.THURSDAY_FIGURES,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 let active=false,ticket=0,owner=null,rounds=[],queue=[],index=0,answers=[],selected=null,nameChoice=null,phase='name',hinted=false,finished=false,kind='quiz',roundId='',syncMessage='';
 const key=u=>'figures-thursday-cloud-v1:'+u;
 const valid=()=>active&&owner&&owner===GameAccount.userId();
 function cache(u,data){try{localStorage.setItem(key(u),JSON.stringify(data))}catch{}}
 async function load(u){try{const data=await GameAccount.api('get_thursday_progress',{},u);cache(u,data.rounds);return {rounds:data.rounds,message:''}}catch{let cached=[];try{cached=JSON.parse(localStorage.getItem(key(u))||'[]');if(!Array.isArray(cached))cached=[]}catch{}return {rounds:cached,message:'Historique hors ligne. Reconnecte-toi à Internet pour actualiser le bilan.'}}}
 function controls(){return `<div class="revision-toolbar"><span class="pill">CONTRÔLE · JEUDI 24 SEPTEMBRE</span><div class="revision-actions">${[['written','Contrôle rédigé'],['quiz','Quiz · 24'],['why','Comprendre'],['targeted','Révision ciblée'],['readiness','Mon niveau'],['cards','Fiches · 24']].map(([id,label])=>`<button class="secondary ${kind===id?'active':''}" id="revision-${id}" aria-pressed="${kind===id}">${label}</button>`).join('')}</div>${syncMessage?'<p class="small" role="status">'+esc(syncMessage)+'</p>':''}</div>`}
 function bindControls(){for(const m of ['written','quiz','why','targeted','readiness','cards'])$('revision-'+m).onclick=()=>begin(m)}
 async function begin(request='written',ids){window.WrittenExam?.stop();if(!GameAccount.requireLogin()){active=false;return}if(Array.isArray(request)){ids=request;request='targeted'}active=true;owner=GameAccount.userId();const u=owner,t=++ticket;kind=request;finished=true;GameAccount.setTestActive(request==='exam');if(kind==='written'){syncMessage='';WrittenExam.start({shell:controls,bind:bindControls});return}$('game').innerHTML='<p role="status">Chargement de ta révision…</p>';const data=await load(u);if(!valid()||t!==ticket)return;rounds=data.rounds;syncMessage=data.message;
  if(kind==='cards'){cards();return}if(kind==='readiness'){readiness();return}
  finished=false;index=0;answers=[];selected=null;nameChoice=null;phase='name';hinted=false;roundId=crypto.randomUUID();
  const ranked=ThursdayLearning.assess(rounds).sort((a,b)=>b.priority-a.priority||Math.random()-.5);
  let pool=ids?bank.filter(f=>ids.includes(f.id)):kind==='targeted'?ranked.slice(0,10).map(f=>bank[f.id]):kind==='why'?ranked.slice(0,12).map(f=>bank[f.id]):bank;
  queue=shuffle(pool).map((f,i)=>{const type=kind==='why'?'example':i%3===0?'definition':'example',exampleIndex=ThursdayLearning.chooseExample(f,rounds),example=f.examples[exampleIndex];const excluded=type==='example'?({'Homéotéleute':['Paronomase'],'Paronomase':['Homéotéleute'],'Adynaton':['Hyperbole'],'Hyperbole':['Adynaton'],'Zeugma':['Syllepse'],'Syllepse':['Zeugma'],'Chiasme':['Antithèse']}[f.name]||[]):[];const options=shuffle([f,...shuffle(bank.filter(x=>x.id!==f.id&&!excluded.includes(x.name))).slice(0,3)]);return {f,type,example,questionId:f.id*100+(type==='definition'?99:exampleIndex),options,reasons:shuffle(options)}});
  render();
 }
 function render(){if(!valid())return;const q=queue[index];$('game').innerHTML=controls()+`<div class="question-top"><span>${kind==='exam'?'Examen · corrections à la fin':kind==='why'?'Identifier, puis expliquer':kind==='targeted'?'Erreurs et figures à revoir':q.type==='definition'?'Définition':'Exemple'}</span><span>${index+1} / ${queue.length}</span></div><progress value="${index}" max="${queue.length}" aria-label="Questions terminées"></progress><h2>${esc(q.type==='definition'?q.f.definition:'« '+q.example[0]+' »')}</h2><p class="prompt">${phase==='reason'?'Pourquoi ? Choisis le mécanisme utilisé.':'Quelle figure de style correspond à '+(q.type==='definition'?'cette définition':'cet exemple')+' ?'}</p><div class="answers">${(phase==='reason'?q.reasons:q.options).map((f,i)=>`<button data-revision-answer="${f.id}"><span class="key">${i+1}</span>${esc(phase==='reason'?f.definition:f.name)}</button>`).join('')}</div><div id="revision-feedback" aria-live="polite" role="status"></div><div class="actions">${kind!=='exam'?'<button class="text-btn" id="revision-hint">Indice</button>':'<span class="small">Sans indice · pas de correction avant le bilan</span>'}<button class="primary hidden" id="revision-next">${index+1===queue.length?'Voir les résultats':'Continuer →'}</button></div><p class="small revision-note">24 figures · XP sauvegardés à la fin de la série. 10 XP par réussite, 5 avec indice, 15 en mode Comprendre. Deux réussites récompensées par figure et par jour, tous modes confondus.</p>`;bindControls();document.querySelectorAll('[data-revision-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.revisionAnswer)));$('revision-next').onclick=next;const hint=$('revision-hint');if(hint){hint.disabled=hinted;hint.onclick=()=>{hinted=true;hint.disabled=true;$('revision-feedback').innerHTML='<div class="feedback">'+esc(q.f.hint)+'</div>'}}
 }
 function answer(id){if(!valid()||finished||selected!==null||!queue[index]?.options.some(f=>f.id===id))return false;const q=queue[index];if(kind==='why'&&phase==='name'){nameChoice=id;phase='reason';Arena.celebrate('tap');render();return true}
  selected=id;const chosen=kind==='why'?nameChoice:id,reason=kind==='why'?id:null,correct=chosen===q.f.id&&(reason===null||reason===q.f.id);answers.push({q,selected:chosen,reasonId:reason,correct,hinted});
  document.querySelectorAll('[data-revision-answer]').forEach(b=>{b.disabled=true;const n=Number(b.dataset.revisionAnswer);if(kind==='exam'){if(n===id)b.classList.add('selected')}else{if(n===q.f.id)b.classList.add('right');else if(n===id)b.classList.add('wrong')}});
  $('revision-feedback').innerHTML=kind==='exam'?'<div class="feedback">Réponse enregistrée.</div>':`<div class="answer-signal ${correct?'success':'retry'}">${correct?'✓ Correct':'↗ '+esc(q.f.name)}</div><div class="feedback ${correct?'good':'bad'}"><p>${esc(q.example[1])}</p>${q.type==='definition'?'<p>Exemple : « '+esc(q.example[0])+' »</p>':''}${kind==='why'&&!correct?'<p>La figure et son explication doivent être justes.</p>':''}</div>`;if($('revision-hint'))$('revision-hint').hidden=true;$('revision-next').classList.remove('hidden');$('revision-next').focus();Arena.celebrate(kind==='exam'?'tap':correct?1:'wrong');return true;
 }
 function next(){if(!valid()||selected===null||finished)return false;index++;selected=null;hinted=false;nameChoice=null;phase='name';if(index===queue.length)summary();else render();return true}
 function summary(){finished=true;GameAccount.setTestActive(false);const correct=answers.filter(a=>a.correct).length,unaided=answers.filter(a=>a.correct&&!a.hinted).length,id=roundId,u=owner;
  const review=answers.filter(a=>!a.correct||a.hinted).map(a=>a.q.f.id);
  $('game').innerHTML=controls()+`<h2>${kind==='exam'?'Résultat de l’examen':'Résultats'}</h2><div class="score">${correct}<span> / ${queue.length}</span></div><p>${unaided} réussite(s) sans indice.${kind==='exam'?' Note : '+(correct/24*20).toFixed(1).replace('.',',')+' / 20.':''}</p><p id="revision-save" role="status">Sauvegarde de la série…</p><div id="rank-notice" class="rank-notice" data-result="round:${id}" role="status" aria-live="polite" hidden></div>${review.length?'<button class="primary" id="revision-retry">Revoir les '+review.length+' figures à reprendre</button>':''}<h3>Corrigé</h3>${answers.map(a=>`<div class="review-item"><b class="${a.correct?'good':'bad'}">${a.correct?'✓':'×'} ${esc(a.q.f.name)}${a.hinted?' · avec indice':''}</b><p>${esc(a.q.type==='definition'?a.q.f.definition:a.q.example[0])}</p>${!a.correct?'<p>Ton choix : '+esc(bank[a.selected].name)+(a.reasonId!==null?' · Explication choisie : '+esc(bank[a.reasonId].definition):'')+'</p>':''}<p>${esc(a.q.example[1])}</p></div>`).join('')}`;bindControls();if($('revision-retry'))$('revision-retry').onclick=()=>begin('targeted',review);
  Arena.complete({id,mode:'thursday_'+kind,answers:answers.map(a=>({questionId:a.q.questionId,selectedId:a.selected,reasonId:a.reasonId,hinted:a.hinted}))},u).then(async earned=>{if(valid()&&roundId===id&&$('revision-save'))$('revision-save').textContent=earned===null?'Sauvegarde en attente. La série sera renvoyée à la reconnexion.':'+'+earned+' XP sauvegardés sur ton compte.';const data=await load(u);if(valid()&&owner===u)rounds=data.rounds});Arena.celebrate('finish');$('game').scrollIntoView({block:'start'});
 }
 function readiness(){finished=true;const rows=ThursdayLearning.assess(rounds),solid=rows.filter(f=>f.status==='Solide').length,due=rows.filter(f=>f.due).length;const exams=rounds.filter(r=>['thursday_exam','thursday_written'].includes(r.mode));const lastExam=exams.at(-1);
  $('game').innerHTML=controls()+`<h2>Ton niveau sur les 24 figures</h2><div class="stat-grid"><div><b>${solid}/24</b><span>figures solides</span></div><div><b>${due}</b><span>à réviser maintenant</span></div><div><b>${lastExam?(lastExam.mode==='thursday_written'?lastExam.answers.reduce((n,a)=>n+(a.writtenScore||0),0)/48*20:lastExam.answers.filter(a=>a.correct).length/24*20).toFixed(1)+'/20':'—'}</b><span>dernier examen</span></div></div><p class="small">Les cinq dernières réponses par figure sur sept jours. « Solide » : au moins trois réussites sans indice, sur deux questions différentes, avec une explication juste et au moins 80 % de réussite. Ce bilan n’est pas une prédiction de ta note.</p><p class="small">Une figure en cours revient le lendemain ; une figure solide revient après trois jours. Une erreur ou un indice la remet à réviser immédiatement.</p><div class="readiness-list">${rows.map(f=>`<button class="readiness-row" data-study-revision="${f.id}"><b>${esc(f.name)}</b><span>${f.status} · ${f.unaided}/${f.recent} sans indice${f.due?' · À réviser':f.nextReview?' · Revoir le '+new Date(f.nextReview).toLocaleDateString('fr-FR',{timeZone:'UTC'}):''}</span></button>`).join('')}</div>`;bindControls();document.querySelectorAll('[data-study-revision]').forEach(b=>b.onclick=()=>begin('targeted',[Number(b.dataset.studyRevision)]));
 }
 function cards(){finished=true;$('game').innerHTML=controls()+'<h2>Les 24 figures du contrôle</h2><div class="revision-cards">'+bank.map(f=>`<details><summary>${esc(f.name)}</summary><p>${esc(f.definition)}</p>${f.examples.map(([text,explanation])=>`<blockquote>${esc(text)}</blockquote><p class="small">${esc(explanation)}</p>`).join('')}</details>`).join('')+'</div>';bindControls()}
 window.addEventListener('game-round-saved',async e=>{if(!valid()||e.detail.owner!==owner||e.detail.id!==roundId||!$('revision-save'))return;const u=owner,id=roundId,data=await load(u);if(!valid()||owner!==u||roundId!==id)return;rounds=data.rounds;const saved=rounds.find(r=>r.id===id);if(saved&&$('revision-save'))$('revision-save').textContent='+'+saved.earned+' XP sauvegardés sur ton compte.'});
 document.addEventListener('keydown',e=>{if(!valid()||finished||selected!==null||e.repeat||$('auth-dialog')?.open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const n=Number(e.key),q=queue[index];if(n>=1&&n<=4&&Number.isInteger(n)){e.preventDefault();answer((phase==='reason'?q.reasons:q.options)[n-1].id)}});
 window.ThursdayRevision={start:begin,stop:()=>{window.WrittenExam?.stop();active=false;ticket++},answer,next,state:()=>kind==='written'?WrittenExam.state():({mode:'thursday',kind,phase,finished,question:index+1,total:queue.length,answered:selected!==null,prompt:queue[index]?(queue[index].type==='definition'?queue[index].f.definition:queue[index].example[0]):null,options:(queue[index]?(phase==='reason'?queue[index].reasons:queue[index].options):[]).map(f=>({id:f.id,name:phase==='reason'?f.definition:f.name}))})};
})();
