/* Scope transcribed from IMG_6439 and IMG_6438, test dated 24/09/2026.
   Definitions follow the sheets. Examples are selected or clarified to isolate the intended mechanism. */
window.THURSDAY_FIGURES = [
 ['Antithèse','Rapprochement de deux idées opposées dans une même phrase.',[['Je vis, je meurs.','Les deux propositions opposent la vie et la mort.'],['Il rit le jour et pleure la nuit.','Deux idées contraires sont réparties dans deux segments.']], 'Les idées opposées sont séparées, contrairement aux mots réunis dans un oxymore.'],
 ['Oxymore','Alliance de deux mots contraires dans un même groupe de mots.',[['Un silence assourdissant.','« Silence » et « assourdissant » sont opposés et réunis dans le même groupe.'],['Cette obscure clarté.','Les termes contraires « obscure » et « clarté » sont associés directement.']], 'Cherche deux mots contraires placés ensemble.'],
 ['Hyperbole','Exagération volontaire.',[['Je meurs de faim.','La faim est exagérée : le locuteur ne meurt pas réellement.'],['Je t’ai appelé mille fois !','Le nombre d’appels est volontairement amplifié.']], 'La réalité est amplifiée.'],
 ['Euphémisme','Atténuation d’une réalité brutale ou choquante.',[['Il nous a quittés, dit-elle pour annoncer son décès.','« Nous a quittés » adoucit l’annonce de la mort.'],['Son entreprise le remercie : il vient d’être licencié.','« Remercier » atténue la réalité du licenciement.']], 'Une expression plus douce remplace une réalité pénible.'],
 ['Anadiplose','Reprise du dernier mot d’une phrase au début de la suivante.',[['Il avait peur. Peur de l’inconnu.','« Peur » termine le premier segment et commence le suivant.'],['Il cherche le bonheur. Le bonheur lui échappe.','La fin d’une phrase est reprise au début de la suivante.']], 'Regarde la jonction entre deux phrases.'],
 ['Épitrochasme','Accumulation de mots courts et frappants, souvent sans verbes.',[['Vite, fort, droit.','Les mots brefs et juxtaposés produisent un rythme rapide.'],['Frappe, saigne, hurle.','Les verbes courts s’accumulent avec un effet frappant.']], 'Une succession rapide de mots très courts.'],
 ['Homéotéleute','Répétition d’une même terminaison sonore dans plusieurs mots proches.',[['Il avance lentement, prudemment, silencieusement.','Les trois mots ont la même terminaison sonore en « -ment ».'],['Une décision, une révision, une conclusion.','Les mots se terminent par le même son « -sion ».']], 'Écoute la fin des mots, plutôt que leur début.'],
 ['Hyperbate','Ajout d’un mot ou d’un groupe après la fin logique de la phrase.',[['Tout le monde était parti. Même lui.','« Même lui » est ajouté après une phrase déjà complète.'],['Je l’aime, cette ville. Tellement.','« Tellement » prolonge un énoncé qui semblait terminé.']], 'La phrase semble finie, puis un élément est ajouté.'],
 ['Prétérition','Dire qu’on ne va pas dire quelque chose, tout en le disant.',[['Je ne vous dirai pas qu’il a triché.','Le locuteur révèle la tricherie en annonçant qu’il ne la révélera pas.'],['Inutile de rappeler qu’il a échoué lamentablement.','Le fait de prétendre ne pas rappeler l’échec le rappelle quand même.']], 'On annonce que l’on va taire ce que l’on évoque justement.'],
 ['Aposiopèse','Rupture ou suspension de phrase traduisant une émotion ou une hésitation.',[['Si jamais tu fais ça, je…','La menace est interrompue avant d’être achevée.'],['Je vais te… mais non, tu ne comprends rien.','La phrase se brise et repart sur une autre idée.']], 'L’énoncé s’interrompt avant sa fin.'],
 ['Antiphrase','Dire le contraire de ce que l’on pense, souvent ironiquement.',[['Bravo ! Tu as encore tout raté.','Le compliment apparent exprime en réalité un reproche.'],['Quel temps magnifique ! dit-il sous une pluie glaciale.','Le contexte montre que le locuteur pense le contraire de ses mots.']], 'Le contexte transforme les mots en leur contraire.'],
 ['Périphrase','Remplacer un mot par une expression qui le désigne.',[['Le roi des animaux dort à l’ombre.','« Le roi des animaux » désigne le lion par une expression.'],['La capitale de la France accueille les visiteurs.','L’expression désigne Paris sans employer son nom.']], 'Plusieurs mots servent à désigner une seule réalité.'],
 ['Hypotypose','Description vivante et imagée d’une scène, comme si on y assistait.',[['Le sang coulait, les corps jonchaient le sol, un soldat rampait vers la porte.','Les détails concrets et les actions rendent la scène presque visible.'],['La porte claque, une tasse éclate, le café se répand ; une main tremblante ramasse les morceaux.','La succession d’actions et de détails donne l’impression d’assister à la scène.']], 'Des détails concrets donnent une scène à voir.'],
 ['Paronomase','Rapprochement de mots aux sons proches mais aux sens différents.',[['Qui se ressemble s’assemble.','« Ressemble » et « assemble » ont des sons proches et des sens différents.'],['Il hésite entre le poison et le poisson.','Les deux mots se ressemblent à l’oreille mais ne désignent pas la même chose.']], 'Des mots presque semblables à l’oreille ont des sens différents.'],
 ['Adynaton','Hyperbole poussée à l’impossible : une exagération irréalisable.',[['Quand les poules auront des dents.','L’image exprime une impossibilité, au-delà de la simple amplification.'],['Je partirai quand les pierres se mettront à parler.','L’événement annoncé est impossible.']], 'L’exagération devient explicitement impossible.'],
 ['Antanaclase','Répétition d’un même mot avec un sens différent.',[['Mon avocat achète un avocat au marché.','Le même mot désigne d’abord le professionnel du droit, puis le fruit.'],['Cette règle de grammaire n’est pas la règle qui mesure ma feuille.','Le même mot est répété : d’abord une prescription, puis un instrument.']], 'Le mot revient plusieurs fois, mais son sens change.'],
 ['Hypallage','Attribution d’un mot à un autre que celui qu’il qualifie logiquement.',[['Un vieillard en or avec une montre fatiguée.','Les qualifications sont déplacées : c’est normalement la montre qui est en or et le vieillard qui est fatigué.'],['Le voyageur parcourait une route fatiguée.','« Fatiguée » qualifie grammaticalement la route, alors que la fatigue concerne le voyageur.']], 'Le qualificatif est attaché au mauvais nom sur le plan logique.'],
 ['Épanadiplose','Reprise, à la fin d’une phrase, du mot qui la commence.',[['L’homme est un loup pour l’homme.','« L’homme » se trouve au début et à la fin du même énoncé.'],['Seul, il attendait dans la salle, seul.','Le même mot encadre une seule phrase.']], 'Le début et la fin d’une même phrase se répondent.'],
 ['Polyptote','Répétition d’un mot sous plusieurs formes grammaticales.',[['Je vis, tu vivras, nous avons vécu.','Le verbe vivre revient sous plusieurs formes conjuguées.'],['Aimer, j’aime ; aimé, je le serai peut-être.','Le même verbe apparaît à l’infinitif, conjugué et au participe passé.']], 'Un même mot revient sous des formes grammaticales différentes.'],
 ['Zeugma','Coordination de termes disparates, souvent concrets et abstraits.',[['Il a perdu sa montre et son sourire.','Un seul verbe relie un objet concret et un élément abstrait.'],['Il prit du ventre et de l’importance.','« Prit » gouverne deux compléments de sens différents.']], 'Un même verbe relie deux compléments qui ne vont pas sur le même plan.'],
 ['Syllepse','Emploi d’un même mot à la fois au sens propre et au sens figuré.',[['Cet homme est droit : sa posture comme sa conduite le montrent.','« Droit », employé une seule fois, désigne à la fois la posture physique et l’honnêteté.'],['Elle est lumineuse : sa robe brille et son intelligence éclaire la discussion.','« Lumineuse » est compris à la fois au sens physique et au sens figuré.']], 'Une seule occurrence du mot porte deux sens en même temps.'],
 ['Chiasme','Croisement de termes selon un schéma ABBA.',[['Il faut manger pour vivre, et non vivre pour manger.','Manger / vivre devient vivre / manger : l’ordre est inversé.'],['En échangeant un regard, un regard en échangeant.','Les mêmes groupes sont repris dans l’ordre inverse.']], 'Repère deux éléments qui reviennent dans l’ordre inverse.'],
 ['Tmésis','Séparation d’un mot composé par intercalation.',[['L’hypo — très — critique.','Dans l’exemple de la fiche, « très » est inséré à l’intérieur de « hypocritique ».'],['L’in — joli — que de ta conduite.','Dans l’exemple de la fiche, un élément est intercalé dans un mot interrompu.']], 'Un mot lui-même est coupé par l’insertion d’un élément.'],
 ['Épanorthose','Rectification ou correction d’un propos pour le renforcer.',[['C’est un héros, non, un dieu !','Le locuteur corrige « héros » par le terme plus fort « dieu ».'],['Il est intelligent, que dis-je, génial !','Le second qualificatif corrige et renforce le premier.']], 'Le locuteur reprend ses propres mots pour les corriger.']
].map(([name,definition,examples,hint],id)=>({id,name,definition,examples,hint}));
