/* Written Thursday practice. Drafts stay scoped to the signed-in account. */
(() => {
 'use strict';
 const bank=window.THURSDAY_FIGURES,$=id=>document.getElementById(id);
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let active=false,owner=null,draft=null,shell=()=>'',bind=()=>{},storageOK=true,busy=false,result=null,notice='',generation=0,pollTimer;
 const key=u=>'figures-written-v1:'+u;
 const valid=()=>active&&owner&&owner===GameAccount.userId();
 function save(){if(!valid())return;try{localStorage.setItem(key(owner),JSON.stringify(draft));storageOK=true}catch{storageOK=false}}
 function fresh(){const ids=bank.map(f=>f.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return {version:1,id:crypto.randomUUID(),index:0,submitted:false,questions:ids.map(id=>({figureId:id,type:Math.random()<.5?'name':'example',exampleIndex:Math.floor(Math.random()*bank[id].examples.length),name:'',definition:'',example:''}))}}
 function usable(d){return d?.version===1&&typeof d.id==='string'&&Number.isInteger(d.index)&&d.index>=0&&d.index<24&&typeof d.submitted==='boolean'&&Array.isArray(d.questions)&&d.questions.length===24&&new Set(d.questions.map(q=>q.figureId)).size===24&&d.questions.every(q=>bank[q.figureId]&&['name','example'].includes(q.type)&&Number.isInteger(q.exampleIndex)&&bank[q.figureId].examples[q.exampleIndex]&&['name','definition','example'].every(k=>typeof q[k]==='string'&&q[k].length<=(k==='name'?80:600)))}
 function start(options={}){if(!GameAccount.requireLogin())return;active=true;owner=GameAccount.userId();generation++;busy=false;result=null;notice='';clearTimeout(pollTimer);shell=options.shell||(()=> '');bind=options.bind||(()=>{});storageOK=true;draft=null;try{const saved=JSON.parse(localStorage.getItem(key(owner))||'null');if(usable(saved))draft=saved}catch{}if(!draft)draft=fresh();GameAccount.setTestActive(!draft.submitted);save();render();if(draft.submitted)recover()}
 function complete(q){return !!q.definition.trim()&&!!(q.type==='name'?q.example.trim():q.name.trim())}
 function status(){return storageOK?'Brouillon enregistré sur cet appareil.':'Le navigateur ne permet pas de sauvegarder le brouillon. Garde cette page ouverte.'}
 function frame(body){$('game').innerHTML=shell()+body;bind()}
 function capture(){if(!valid()||draft.submitted)return;const q=draft.questions[draft.index];for(const k of ['name','definition','example']){const input=$('written-'+k);if(input)q[k]=input.value.slice(0,k==='name'?80:600)}save();if($('written-storage'))$('written-storage').textContent=status()}
 function render(){if(!valid())return;if(draft.submitted){returned();return}const q=draft.questions[draft.index],f=bank[q.figureId];frame(`<div class="question-top"><span>Contrôle rédigé · jeudi 24 septembre</span><span>${draft.index+1} / 24</span></div><progress value="${draft.questions.filter(complete).length}" max="24" aria-label="Questions complétées"></progress><h2>${esc(q.type==='name'?f.name:'« '+f.examples[q.exampleIndex][0]+' »')}</h2><p>${q.type==='name'?'Donne la définition de cette figure et écris un exemple.':'Nomme la figure de style et donne sa définition.'}</p><form id="written-form" class="written-form">${q.type==='example'?`<label for="written-name">Nom de la figure</label><input id="written-name" maxlength="80" autocomplete="off" value="${esc(q.name)}">`:''}<label for="written-definition">Définition avec tes mots</label><textarea id="written-definition" maxlength="600" rows="3">${esc(q.definition)}</textarea>${q.type==='name'?`<label for="written-example">Ton exemple</label><textarea id="written-example" maxlength="600" rows="3">${esc(q.example)}</textarea>`:''}<div class="actions"><button type="button" class="secondary" id="written-previous" ${draft.index===0?'disabled':''}>Précédente</button><button type="submit" class="primary">${draft.index===23?'Relire ma copie':'Suivante →'}</button></div></form><p class="small" id="written-storage" role="status">${status()}</p><p class="small">Tu peux laisser une question vide et y revenir avant de rendre ta copie. Aucun corrigé pendant le contrôle.</p><button class="text-btn" id="written-review">Voir toutes mes réponses</button>`);
  $('written-form').onsubmit=e=>{e.preventDefault();capture();if(draft.index===23)review();else{draft.index++;save();render()}};$('written-previous').onclick=()=>{capture();draft.index--;save();render()};$('written-review').onclick=()=>{capture();review()};document.querySelectorAll('#written-form input,#written-form textarea').forEach(el=>el.addEventListener('input',capture));
 }
 function review(){if(!valid())return;const missing=draft.questions.filter(q=>!complete(q)).length;frame(`<h2>Relire ma copie</h2><p>${24-missing} / 24 questions complètes.${missing?' Tu peux encore compléter les '+missing+' autres.':''}</p><div class="written-review">${draft.questions.map((q,i)=>{const f=bank[q.figureId];return `<article class="review-item"><h3>${i+1}. ${esc(q.type==='name'?f.name:f.examples[q.exampleIndex][0])}</h3>${q.type==='example'?'<p><b>Nom :</b> '+esc(q.name||'Sans réponse')+'</p>':''}<p><b>Définition :</b> ${esc(q.definition||'Sans réponse')}</p>${q.type==='name'?'<p><b>Exemple :</b> '+esc(q.example||'Sans réponse')+'</p>':''}<button class="secondary" data-written-edit="${i}">Modifier la réponse ${i+1}</button></article>`}).join('')}</div><button class="primary" id="written-submit">Rendre et corriger ma copie${missing?' avec '+missing+' question(s) incomplète(s)':''}</button>`);document.querySelectorAll('[data-written-edit]').forEach(b=>b.onclick=()=>{draft.index=Number(b.dataset.writtenEdit);save();render()});$('written-submit').onclick=()=>{if(!valid()||draft.submitted)return;draft.submitted=true;save();GameAccount.setTestActive(false);returned();grade()}}
 function resultView(){const pending=result.items.filter(i=>i.uncertain).length;return `<h2>Ton corrigé</h2><div class="score">${Number(result.score).toFixed(1).replace('.',',')}<span> / 20</span></div><p>Note indicative · correction par IA${pending?' · '+pending+' réponse(s) à vérifier, non comptée(s) dans la note':''}.</p><p>+${Number(result.earned)} XP sauvegardés. Les réponses entièrement justes rapportent des XP, dans la limite quotidienne habituelle.</p><div id="rank-notice" class="rank-notice" data-result="round:${esc(draft.id)}" role="status" aria-live="polite" hidden></div>${draft.questions.map((q,index)=>{const f=bank[q.figureId],g=result.items.find(i=>i.figureId===q.figureId),points=g.definitionScore+g.answerScore;return `<article class="review-item"><h3>${index+1}. ${esc(f.name)} · ${g.uncertain?'À vérifier':points===2?'Juste':points===0?'À revoir':'Partiellement juste'}</h3><p>${esc(q.type==='name'?f.name:f.examples[q.exampleIndex][0])}</p><p><b>Ta définition (${g.definitionScore}/1) :</b> ${esc(q.definition||'Sans réponse')}</p><p><b>${q.type==='name'?'Ton exemple':'Ton identification'} (${g.answerScore}/1) :</b> ${esc((q.type==='name'?q.example:q.name)||'Sans réponse')}</p><p>${esc(g.feedback)}</p><details><summary>Revoir le cours</summary><p>${esc(f.definition)}</p><p>${esc(f.examples[q.exampleIndex][0])}</p></details></article>`}).join('')}`}
 function returned(){if(!valid())return;frame((result?resultView():`<h2>${busy?'Correction en cours…':'Ta copie est enregistrée sur cet appareil'}</h2><p>${busy?'Le correcteur lit tes réponses. Cela peut prendre environ une minute.':'La correction apparaît ici après l’envoi.'}</p><p id="written-grade-status" role="status">${esc(notice)}</p><button class="primary" id="written-grade" ${busy?'disabled':''}>${busy?'Correction en cours…':'Corriger ma copie'}</button>`)+`<p class="small">Tes réponses sont envoyées à OpenAI pour la correction, sans ton pseudo ni ton adresse e-mail. Une correction peut se tromper : compare les remarques avec ton cours.</p><button class="secondary" id="written-new" ${busy?'disabled':''}>Nouvelle copie</button><div id="written-new-confirm"></div>`);if($('written-grade'))$('written-grade').onclick=grade;$('written-new').onclick=()=>{$('written-new-confirm').innerHTML='<p>Une nouvelle copie remplacera celle conservée sur cet appareil.</p><button class="primary" id="written-confirm-new">Commencer une nouvelle copie</button>';$('written-confirm-new').onclick=()=>{if(!valid()||busy)return;generation++;draft=fresh();result=null;notice='';save();GameAccount.setTestActive(true);render()}}}
 function displayResult(data){result=data;busy=false;notice='';returned();Arena.refresh?.();window.dispatchEvent(new CustomEvent('game-round-saved',{detail:{owner,id:draft.id}}));window.RankNotice?.check({round:draft.id},owner)}
 async function recover(attempt=0){const t=generation,u=owner,id=draft.id;try{const saved=await GameAccount.api('get_written_exam',{p_id:id},u);if(!valid()||t!==generation)return;if(saved?.status==='graded'){displayResult(saved.result);return}if(saved?.status==='pending'&&attempt<24){busy=true;notice='Correction en cours. Tes réponses sont conservées.';returned();pollTimer=setTimeout(()=>recover(attempt+1),5000);return}busy=false;notice=saved?.status==='failed'?'La correction a été interrompue. Tu peux réessayer.':saved?.status==='pending'?'La correction prend plus de temps que prévu. Réessaie dans un instant.':'';returned()}catch{if(valid()&&t===generation){busy=false;notice='Connexion indisponible. Ta copie est conservée.';returned()}}}
 async function grade(){if(!valid()||busy||result)return;busy=true;notice='';const t=generation,u=owner,id=draft.id;returned();try{const data=await GameAccount.gradeWritten(id,draft.questions,u);if(!valid()||t!==generation)return;if(data.status==='graded')displayResult(data.result);else recover()}catch(e){if(!valid()||t!==generation)return;busy=false;notice=e.message||'Correction indisponible. Ta copie est conservée.';returned()}}
 window.WrittenExam={start,stop:()=>{capture();generation++;clearTimeout(pollTimer);active=false;owner=null},state:()=>({mode:'thursday',kind:'written',finished:!!draft?.submitted,question:(draft?.index||0)+1,total:24,options:[]})};
 window.addEventListener('pagehide',capture);window.addEventListener('account-identity-changed',()=>{if(owner!==GameAccount.userId()){generation++;clearTimeout(pollTimer);active=false;owner=null;draft=null}});
})();
