const {JSDOM}=require('jsdom'),fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
(async()=>{
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;let user='a',calls=0,resolve;
 w.GameAccount={userId:()=>user,requireLogin:()=>!!user,setTestActive:()=>{},api:async()=>null,gradeWritten:async(id,answers,u)=>{calls++;assert.equal(u,'a');return new Promise(r=>{resolve=()=>r({status:'graded',result:{id,score:15.5,earned:120,items:answers.map(q=>({figureId:q.figureId,answerScore:1,definitionScore:.5,uncertain:false,feedback:'<img src=x onerror=alert(1)>'}))}})})}};
 w.Arena={refresh:()=>{}};const ctx=dom.getInternalVMContext();for(const f of ['thursday-data.js','written-exam.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
 const $=id=>w.document.getElementById(id),tick=()=>new Promise(r=>setTimeout(r,10));const saved=()=>JSON.parse(w.localStorage.getItem('figures-written-v1:'+user));
 w.WrittenExam.start();let d=saved();assert.equal(new Set(d.questions.map(q=>q.figureId)).size,24);assert.ok($('written-form'));assert.equal(w.document.querySelectorAll('[data-revision-answer]').length,0);
 // Deterministic uneven sequence proves runs of the same format survive rendering/restoration.
 d.questions.forEach((q,i)=>q.type=i<18?'name':'example');w.WrittenExam.stop();w.localStorage.setItem('figures-written-v1:a',JSON.stringify(d));w.WrittenExam.start();
 for(let i=0;i<24;i++){assert.equal(!!$('written-name'),i>=18);assert.equal(!!$('written-example'),i<18);for(const k of ['name','definition','example'])if($('written-'+k)){$('written-'+k).value=k==='definition'?'Définition <script>alert(1)</script>':'Ma réponse';$('written-'+k).dispatchEvent(new w.Event('input'))}assert.equal(w.document.querySelectorAll('.right,.wrong,.feedback').length,0);$('written-form').dispatchEvent(new w.Event('submit',{cancelable:true}));}
 assert.ok($('written-submit'));assert.equal(w.document.querySelectorAll('#game script').length,0);w.document.querySelector('[data-written-edit="0"]').click();assert.equal($('written-definition').value,'Définition <script>alert(1)</script>');w.WrittenExam.stop();w.WrittenExam.start();assert.equal($('written-definition').value,'Définition <script>alert(1)</script>');$('written-review').click();$('written-submit').click();assert.equal(calls,1);assert.equal($('written-grade').disabled,true);$('written-grade').click();assert.equal(calls,1);resolve();await tick();assert.match($('game').textContent,/15,5/);assert.match($('game').textContent,/120 XP/);assert.equal(w.document.querySelectorAll('#game img').length,0);
 user='b';w.dispatchEvent(new w.Event('account-identity-changed'));w.WrittenExam.start();assert.equal($('written-definition').value,'');assert.equal(saved().submitted,false);
 // The guest cannot start an exam or submit another account's saved answers.
 w.WrittenExam.stop();$('game').innerHTML='';user=null;w.WrittenExam.start();assert.equal($('written-form'),null);
 user='c';w.GameAccount.gradeWritten=async()=>{throw Error('Réseau indisponible')};w.WrittenExam.start();$('written-review').click();$('written-submit').click();await tick();assert.match($('written-grade-status').textContent,/Réseau/);assert.equal(saved().submitted,true);assert.equal($('written-grade').disabled,false);
 w.close();console.log('PASS: written fields, 24 unique figures, uneven random formats, editable review, draft restoration, no early correction, single submit, escaped feedback, account isolation and recoverable network failure.');
})().catch(e=>{console.error(e);process.exit(1)});
